theme: jekyll-theme-minimal
title: Self Study Soldier Blog
description: ROK Airforce (5.2024~) 
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-WMCRGNM0HB"
    anonymize_ip         : # true, false (default)
